2022-11-27 21:50:04,933 - MC_logger - INFO - Initialization of a MC object with the following parameters has been carried out.
{
    "N_experiments": 10,
    "parallel": {
        "n_jobs": 10,
        "verbose": 11
    },
    "experiment": {
        "cluster_number_range": [
            1,
            6
        ],
        "min_datapoints": 5,
        "cluster_size_range": [
            1,
            100
        ],
        "exp_scale_range": [
            0.001,
            1
        ],
        "norm_loc_range": [
            0.5,
            7
        ],
        "norm_scale_range": [
            0.1,
            1
        ]
    },
    "em": {
        "max_reiterations": 50,
        "em_algorithm": {
            "em_tol": 1e-05,
            "max_iter": 100,
            "min_mix_coef": 0.02,
            "abs_tol_params": 1e-08,
            "minimizer": {
                "maxiter": 100
            }
        }
    },
    "cluster_init": {
        "N_cluster_max": 12,
        "N_runs_per_clusternumber": 10,
        "init_routine": "random_inside"
    }
}
2022-11-27 21:50:09,103 - MC_logger - INFO - Starting the clustering of experimental data batch with init_routine random_inside.

2022-11-27 21:50:13,635 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 115, in _cluster_experiment
    em.run(df_experiment, cluster_init=cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 75, in run
    self._run_from_Cluster_Init(X, cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 87, in _run_from_Cluster_Init
    (mixtures, iterations), execution_time = run_EM(X, initial_values_array, **self.params.em_algorithm.get_dict())
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\execution_time_decorator.py", line 9, in timeit_wrapper
    result = func(*args, **kwargs)
TypeError: run_EM() got an unexpected keyword argument 'minimizer'
2022-11-27 21:50:13,723 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 115, in _cluster_experiment
    em.run(df_experiment, cluster_init=cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 75, in run
    self._run_from_Cluster_Init(X, cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 87, in _run_from_Cluster_Init
    (mixtures, iterations), execution_time = run_EM(X, initial_values_array, **self.params.em_algorithm.get_dict())
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\execution_time_decorator.py", line 9, in timeit_wrapper
    result = func(*args, **kwargs)
TypeError: run_EM() got an unexpected keyword argument 'minimizer'
2022-11-27 21:50:13,728 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 115, in _cluster_experiment
    em.run(df_experiment, cluster_init=cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 75, in run
    self._run_from_Cluster_Init(X, cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 87, in _run_from_Cluster_Init
    (mixtures, iterations), execution_time = run_EM(X, initial_values_array, **self.params.em_algorithm.get_dict())
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\execution_time_decorator.py", line 9, in timeit_wrapper
    result = func(*args, **kwargs)
TypeError: run_EM() got an unexpected keyword argument 'minimizer'
2022-11-27 21:50:13,730 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 115, in _cluster_experiment
    em.run(df_experiment, cluster_init=cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 75, in run
    self._run_from_Cluster_Init(X, cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 87, in _run_from_Cluster_Init
    (mixtures, iterations), execution_time = run_EM(X, initial_values_array, **self.params.em_algorithm.get_dict())
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\execution_time_decorator.py", line 9, in timeit_wrapper
    result = func(*args, **kwargs)
TypeError: run_EM() got an unexpected keyword argument 'minimizer'
2022-11-27 21:50:13,768 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 115, in _cluster_experiment
    em.run(df_experiment, cluster_init=cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 75, in run
    self._run_from_Cluster_Init(X, cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 87, in _run_from_Cluster_Init
    (mixtures, iterations), execution_time = run_EM(X, initial_values_array, **self.params.em_algorithm.get_dict())
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\execution_time_decorator.py", line 9, in timeit_wrapper
    result = func(*args, **kwargs)
TypeError: run_EM() got an unexpected keyword argument 'minimizer'
2022-11-27 21:50:13,773 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 115, in _cluster_experiment
    em.run(df_experiment, cluster_init=cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 75, in run
    self._run_from_Cluster_Init(X, cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 87, in _run_from_Cluster_Init
    (mixtures, iterations), execution_time = run_EM(X, initial_values_array, **self.params.em_algorithm.get_dict())
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\execution_time_decorator.py", line 9, in timeit_wrapper
    result = func(*args, **kwargs)
TypeError: run_EM() got an unexpected keyword argument 'minimizer'
2022-11-27 21:50:13,782 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 115, in _cluster_experiment
    em.run(df_experiment, cluster_init=cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 75, in run
    self._run_from_Cluster_Init(X, cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 87, in _run_from_Cluster_Init
    (mixtures, iterations), execution_time = run_EM(X, initial_values_array, **self.params.em_algorithm.get_dict())
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\execution_time_decorator.py", line 9, in timeit_wrapper
    result = func(*args, **kwargs)
TypeError: run_EM() got an unexpected keyword argument 'minimizer'
2022-11-27 21:50:13,788 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 115, in _cluster_experiment
    em.run(df_experiment, cluster_init=cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 75, in run
    self._run_from_Cluster_Init(X, cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 87, in _run_from_Cluster_Init
    (mixtures, iterations), execution_time = run_EM(X, initial_values_array, **self.params.em_algorithm.get_dict())
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\execution_time_decorator.py", line 9, in timeit_wrapper
    result = func(*args, **kwargs)
TypeError: run_EM() got an unexpected keyword argument 'minimizer'
2022-11-27 21:50:13,803 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 115, in _cluster_experiment
    em.run(df_experiment, cluster_init=cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 75, in run
    self._run_from_Cluster_Init(X, cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 87, in _run_from_Cluster_Init
    (mixtures, iterations), execution_time = run_EM(X, initial_values_array, **self.params.em_algorithm.get_dict())
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\execution_time_decorator.py", line 9, in timeit_wrapper
    result = func(*args, **kwargs)
TypeError: run_EM() got an unexpected keyword argument 'minimizer'
2022-11-27 21:50:13,889 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 115, in _cluster_experiment
    em.run(df_experiment, cluster_init=cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 75, in run
    self._run_from_Cluster_Init(X, cluster_init)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\em_algorithm\em_class.py", line 87, in _run_from_Cluster_Init
    (mixtures, iterations), execution_time = run_EM(X, initial_values_array, **self.params.em_algorithm.get_dict())
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\execution_time_decorator.py", line 9, in timeit_wrapper
    result = func(*args, **kwargs)
TypeError: run_EM() got an unexpected keyword argument 'minimizer'
2022-11-27 21:50:13,891 - MC_logger - INFO - Clustering with init routine random_inside has finished.
2022-11-27 21:50:13,891 - MC_logger - INFO - 
Clustering successfull; starting processing of results
2022-11-27 21:50:13,891 - MC_logger - ERROR - 
There was an exception in  _merge_parallel_results
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 135, in _merge_parallel_results
    merged_result = {key: [] for key in parallel_results[0].keys()}
AttributeError: 'NoneType' object has no attribute 'keys'
2022-11-27 21:50:13,892 - MC_logger - ERROR - 
There was an exception in  _create_df_from_results
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 148, in _create_df_from_results
    df_result = pd.DataFrame.from_dict({key: val for key, val in merged_results.items() if key not in non_df_cols})
AttributeError: 'NoneType' object has no attribute 'items'
2022-11-27 21:50:13,892 - MC_logger - ERROR - 
There was an exception in  _process_parallel_results
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 125, in _process_parallel_results
    df_results, model_data = self._create_df_from_results(merged_results)
TypeError: cannot unpack non-iterable NoneType object
2022-11-27 21:50:13,892 - MC_logger - ERROR - 
There was an exception in  run
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 75, in run
    self.df_results, self.model_data = self._process_parallel_results(parallel_results)
TypeError: cannot unpack non-iterable NoneType object
