2022-11-27 21:55:43,555 - MC_logger - INFO - Initialization of a MC object with the following parameters has been carried out.
{
    "N_experiments": 10,
    "parallel": {
        "n_jobs": 10,
        "verbose": 11
    },
    "experiment": {
        "cluster_number_range": [
            1,
            6
        ],
        "min_datapoints": 5,
        "cluster_size_range": [
            1,
            100
        ],
        "exp_scale_range": [
            0.001,
            1
        ],
        "norm_loc_range": [
            0.5,
            7
        ],
        "norm_scale_range": [
            0.1,
            1
        ]
    },
    "em": {
        "max_reiterations": 50,
        "em_algorithm": {
            "em_tol": 1e-05,
            "max_iter": 100,
            "min_mix_coef": 0.02,
            "abs_tol_params": 1e-08,
            "minimizer_options": {
                "maxiter": 100
            }
        }
    },
    "cluster_init": {
        "N_cluster_max": 12,
        "N_runs_per_clusternumber": 10,
        "init_routine": "random_inside"
    }
}
2022-11-27 21:55:52,446 - MC_logger - INFO - Starting the clustering of experimental data batch with init_routine random_inside.

2022-11-27 21:56:37,901 INFO     Experiment 2 has finished.
2022-11-27 21:57:00,948 INFO     Experiment 1 has finished.
2022-11-27 21:57:14,752 INFO     Experiment 7 has finished.
2022-11-27 21:57:42,093 INFO     Experiment 8 has finished.
2022-11-27 21:57:59,748 INFO     Experiment 6 has finished.
2022-11-27 21:59:36,509 INFO     Experiment 0 has finished.
2022-11-27 22:02:43,296 INFO     Experiment 4 has finished.
2022-11-27 22:04:38,621 INFO     Experiment 5 has finished.
2022-11-27 22:05:53,696 INFO     Experiment 3 has finished.
2022-11-27 22:08:53,205 INFO     Experiment 9 has finished.
2022-11-27 22:08:53,211 - MC_logger - INFO - Clustering with init routine random_inside has finished.
2022-11-27 22:08:53,211 - MC_logger - INFO - 
Clustering successfull; starting processing of results
2022-11-27 22:08:53,218 - MC_logger - ERROR - 
There was an exception in  _include_data_from_true_models
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 156, in _include_data_from_true_models
    model_data["init_routine"] = self.cluster_init_params.init_routine
AttributeError: 'MC' object has no attribute 'cluster_init_params'
2022-11-27 22:08:53,219 - MC_logger - ERROR - 
There was an exception in  _process_parallel_results
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 128, in _process_parallel_results
    df_results = self._include_true_clusternumber(df_results, model_data)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 163, in _include_true_clusternumber
    df_results.loc[idx, "True_N_Cluster"] = len(model_data["datasets"][dataset].cluster.unique())
TypeError: 'NoneType' object is not subscriptable
2022-11-27 22:08:53,219 - MC_logger - ERROR - 
There was an exception in  run
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 75, in run
    self.df_results, self.model_data = self._process_parallel_results(parallel_results)
TypeError: cannot unpack non-iterable NoneType object
2022-11-27 22:10:34,754 - MC_logger - INFO - Initialization of a MC object with the following parameters has been carried out.
{
    "N_experiments": 10,
    "parallel": {
        "n_jobs": 10,
        "verbose": 11
    },
    "experiment": {
        "cluster_number_range": [
            1,
            6
        ],
        "min_datapoints": 5,
        "cluster_size_range": [
            1,
            100
        ],
        "exp_scale_range": [
            0.001,
            1
        ],
        "norm_loc_range": [
            0.5,
            7
        ],
        "norm_scale_range": [
            0.1,
            1
        ]
    },
    "em": {
        "max_reiterations": 50,
        "em_algorithm": {
            "em_tol": 1e-05,
            "max_iter": 100,
            "min_mix_coef": 0.02,
            "abs_tol_params": 1e-08,
            "minimizer_options": {
                "maxiter": 100
            }
        }
    },
    "cluster_init": {
        "N_cluster_max": 3,
        "N_runs_per_clusternumber": 2,
        "init_routine": "random_inside"
    }
}
2022-11-27 22:10:40,591 - MC_logger - INFO - Starting the clustering of experimental data batch with init_routine random_inside.

2022-11-27 22:10:43,818 INFO     Experiment 1 has finished.
2022-11-27 22:10:45,970 INFO     Experiment 8 has finished.
2022-11-27 22:10:46,108 INFO     Experiment 3 has finished.
2022-11-27 22:10:46,558 INFO     Experiment 6 has finished.
2022-11-27 22:10:47,213 INFO     Experiment 4 has finished.
2022-11-27 22:10:47,283 INFO     Experiment 5 has finished.
2022-11-27 22:10:47,452 INFO     Experiment 9 has finished.
2022-11-27 22:10:47,495 INFO     Experiment 7 has finished.
2022-11-27 22:10:47,571 INFO     Experiment 0 has finished.
2022-11-27 22:10:48,169 INFO     Experiment 2 has finished.
2022-11-27 22:10:48,170 - MC_logger - INFO - Clustering with init routine random_inside has finished.
2022-11-27 22:10:48,171 - MC_logger - INFO - 
Clustering successfull; starting processing of results
2022-11-27 22:10:48,175 - MC_logger - ERROR - 
There was an exception in  _include_data_from_true_models
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 156, in _include_data_from_true_models
    model_data["init_routine"] = self.params.cluster_init.init_routine
AttributeError: 'MC' object has no attribute 'cluster_init_params'
2022-11-27 22:10:48,176 - MC_logger - ERROR - 
There was an exception in  _process_parallel_results
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 128, in _process_parallel_results
    df_results = self._include_true_clusternumber(df_results, model_data)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 163, in _include_true_clusternumber
    df_results.loc[idx, "True_N_Cluster"] = len(model_data["datasets"][dataset].cluster.unique())
TypeError: 'NoneType' object is not subscriptable
2022-11-27 22:10:48,176 - MC_logger - ERROR - 
There was an exception in  run
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 75, in run
    self.df_results, self.model_data = self._process_parallel_results(parallel_results)
TypeError: cannot unpack non-iterable NoneType object
