2022-11-27 21:43:36,747 - MC_logger - INFO - Initialization of a MC object with the following parameters has been carried out.
{
    "N_experiments": 10,
    "parallel": {
        "n_jobs": 10,
        "verbose": 11
    },
    "experiment": {
        "cluster_number_range": [
            1,
            6
        ],
        "min_datapoints": 5,
        "cluster_size_range": [
            1,
            100
        ],
        "exp_scale_range": [
            0.001,
            1
        ],
        "norm_loc_range": [
            0.5,
            7
        ],
        "norm_scale_range": [
            0.1,
            1
        ]
    },
    "em": {
        "max_reiterations": 50,
        "em_algorithm": {
            "em_tol": 1e-05,
            "max_iter": 100,
            "min_mix_coef": 0.02,
            "abs_tol_params": 1e-08,
            "minimizer": {
                "maxiter": 100
            }
        }
    },
    "cluster_init": {
        "N_cluster_max": 12,
        "N_runs_per_clusternumber": 10,
        "init_routine": "random_inside"
    }
}
2022-11-27 21:43:38,870 - MC_logger - INFO - Starting the clustering of experimental data batch with init_routine random_inside.

2022-11-27 21:43:42,292 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 113, in _cluster_experiment
    cluster_init.sample()
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\init_class.py", line 67, in sample
    sampled_init_params = self.Routine.get_sampled_init_params(self.possible_starting_values, self.params.N_cluster_max, self.params.N_runs_per_clusternumber)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\algorithms\rnd_inside.py", line 39, in get_sampled_init_params
    for K in range(1, K_max+1):
TypeError: unsupported operand type(s) for +: 'dict' and 'int'
2022-11-27 21:43:42,305 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 113, in _cluster_experiment
    cluster_init.sample()
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\init_class.py", line 67, in sample
    sampled_init_params = self.Routine.get_sampled_init_params(self.possible_starting_values, self.params.N_cluster_max, self.params.N_runs_per_clusternumber)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\algorithms\rnd_inside.py", line 39, in get_sampled_init_params
    for K in range(1, K_max+1):
TypeError: unsupported operand type(s) for +: 'dict' and 'int'
2022-11-27 21:43:42,315 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 113, in _cluster_experiment
    cluster_init.sample()
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\init_class.py", line 67, in sample
    sampled_init_params = self.Routine.get_sampled_init_params(self.possible_starting_values, self.params.N_cluster_max, self.params.N_runs_per_clusternumber)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\algorithms\rnd_inside.py", line 39, in get_sampled_init_params
    for K in range(1, K_max+1):
TypeError: unsupported operand type(s) for +: 'dict' and 'int'
2022-11-27 21:43:42,322 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 113, in _cluster_experiment
    cluster_init.sample()
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\init_class.py", line 67, in sample
    sampled_init_params = self.Routine.get_sampled_init_params(self.possible_starting_values, self.params.N_cluster_max, self.params.N_runs_per_clusternumber)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\algorithms\rnd_inside.py", line 39, in get_sampled_init_params
    for K in range(1, K_max+1):
TypeError: unsupported operand type(s) for +: 'dict' and 'int'
2022-11-27 21:43:42,331 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 113, in _cluster_experiment
    cluster_init.sample()
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\init_class.py", line 67, in sample
    sampled_init_params = self.Routine.get_sampled_init_params(self.possible_starting_values, self.params.N_cluster_max, self.params.N_runs_per_clusternumber)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\algorithms\rnd_inside.py", line 39, in get_sampled_init_params
    for K in range(1, K_max+1):
TypeError: unsupported operand type(s) for +: 'dict' and 'int'
2022-11-27 21:43:42,336 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 113, in _cluster_experiment
    cluster_init.sample()
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\init_class.py", line 67, in sample
    sampled_init_params = self.Routine.get_sampled_init_params(self.possible_starting_values, self.params.N_cluster_max, self.params.N_runs_per_clusternumber)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\algorithms\rnd_inside.py", line 39, in get_sampled_init_params
    for K in range(1, K_max+1):
TypeError: unsupported operand type(s) for +: 'dict' and 'int'
2022-11-27 21:43:42,372 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 113, in _cluster_experiment
    cluster_init.sample()
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\init_class.py", line 67, in sample
    sampled_init_params = self.Routine.get_sampled_init_params(self.possible_starting_values, self.params.N_cluster_max, self.params.N_runs_per_clusternumber)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\algorithms\rnd_inside.py", line 39, in get_sampled_init_params
    for K in range(1, K_max+1):
TypeError: unsupported operand type(s) for +: 'dict' and 'int'
2022-11-27 21:43:42,374 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 113, in _cluster_experiment
    cluster_init.sample()
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\init_class.py", line 67, in sample
    sampled_init_params = self.Routine.get_sampled_init_params(self.possible_starting_values, self.params.N_cluster_max, self.params.N_runs_per_clusternumber)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\algorithms\rnd_inside.py", line 39, in get_sampled_init_params
    for K in range(1, K_max+1):
TypeError: unsupported operand type(s) for +: 'dict' and 'int'
2022-11-27 21:43:42,390 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 113, in _cluster_experiment
    cluster_init.sample()
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\init_class.py", line 67, in sample
    sampled_init_params = self.Routine.get_sampled_init_params(self.possible_starting_values, self.params.N_cluster_max, self.params.N_runs_per_clusternumber)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\algorithms\rnd_inside.py", line 39, in get_sampled_init_params
    for K in range(1, K_max+1):
TypeError: unsupported operand type(s) for +: 'dict' and 'int'
2022-11-27 21:43:42,401 ERROR    
There was an exception in  _cluster_experiment
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 113, in _cluster_experiment
    cluster_init.sample()
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\init_class.py", line 67, in sample
    sampled_init_params = self.Routine.get_sampled_init_params(self.possible_starting_values, self.params.N_cluster_max, self.params.N_runs_per_clusternumber)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\cluster_initialization\algorithms\rnd_inside.py", line 39, in get_sampled_init_params
    for K in range(1, K_max+1):
TypeError: unsupported operand type(s) for +: 'dict' and 'int'
2022-11-27 21:43:42,402 - MC_logger - INFO - Clustering with init routine random_inside has finished.
2022-11-27 21:43:42,402 - MC_logger - INFO - 
Clustering successfull; starting processing of results
2022-11-27 21:43:42,403 - MC_logger - ERROR - 
There was an exception in  _merge_parallel_results
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 135, in _merge_parallel_results
    merged_result = {key: [] for key in parallel_results[0].keys()}
AttributeError: 'NoneType' object has no attribute 'keys'
2022-11-27 21:43:42,403 - MC_logger - ERROR - 
There was an exception in  _create_df_from_results
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 148, in _create_df_from_results
    df_result = pd.DataFrame.from_dict({key: val for key, val in merged_results.items() if key not in non_df_cols})
AttributeError: 'NoneType' object has no attribute 'items'
2022-11-27 21:43:42,403 - MC_logger - ERROR - 
There was an exception in  _process_parallel_results
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 125, in _process_parallel_results
    df_results, model_data = self._create_df_from_results(merged_results)
TypeError: cannot unpack non-iterable NoneType object
2022-11-27 21:43:42,404 - MC_logger - ERROR - 
There was an exception in  run
Traceback (most recent call last):
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\miscellaneous\exception_handler_decorator.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\HydraJ\Documents\Uni\Bachelor&Master  Physik\BA_Arbeit\Code\mc_simulation\mc_class.py", line 75, in run
    self.df_results, self.model_data = self._process_parallel_results(parallel_results)
TypeError: cannot unpack non-iterable NoneType object
